version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755

hooks:
  AfterInstall:
    - location: after_install.sh
      timeout: 150
      runas: root