name: Make Docker Container For React
on: push
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
        # 코드 다운로드
      - name: Checkout
        uses: actions/checkout@v4.1.1

        # Enviroment Check
      - name: Checking Enviroment
        run:
          echo "DOCKER_HUB_ID"
          echo "DOCKER_HUB_ACCESS_TOKEN"

        # Docker Image build
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.0.0
        
      - run: ls -al
