name: Make Docker Container For React
on: push
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
        # 코드 다운로드
      - name: Checkout
        uses: actions/checkout@v4.1.1

        # Enviroment Check
      - name: Checking Enviroment
        run:
          echo "echo DOCKER_HUB_ID=${{secrets.DOCKER_HUB_ID}} > .env"
          echo "echo DOCKER_HUB_ACCESS_TOKEN=${{secrets.DOCKER_HUB_ACCESS_TOKEN}} > .env"
          cat .env

        # Docker Image build
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.0.0
        
      - name: Check Files
        run:
          ls -al

      - name: Check Docker Images
        run:
          docker images
