name: Make Docker Container For React
on: push
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      # 코드 다운로드
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Check Files - Before
        run: ls -al

      ##### Enviroment Settings
      
      - name: Setting Enviroment - DOCKER_HUB_ID
        run:
          echo "DOCKER_HUB_ID=${{secrets.DOCKER_HUB_ID}}" >> .env
          
      - name: Setting Enviroment - DOCKER_HUB_ACCESS_TOKEN
        run:
          echo "DOCKER_HUB_ACCESS_TOKEN=${{secrets.DOCKER_HUB_ACCESS_TOKEN}}" >> .env
          
      ##### Enviroment Settings

      # Docker Buildx Set
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.0.0

      # Docker Hub Login
      - name: Login to DockerHub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{secrets.DOCKER_HUB_ID}}
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}

      # Build and push Docker images
      - name: Build and push Docker images
        uses: docker/build-push-action@v5.1.0
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64, linux/arm64
          push: ture
          tags: martinslee/devops_class_flask:latest

      - name: Check Files - After
        run: ls -al

      - name: Check Enviroment
        run: cat .env
